### ISSUE TITLE
Pretrained models required

### ISSUE THREAD

**Issue by priya-velu5** [franciszchen/SRD-SAI#1]
In the file train_srd.py (line 423) : Where can I find these pre-trained models?     

sr_model.load_state_dict(torch.load('sr pre-trained pth'))  
pretrained_low_dict= torch.load('pre-trained resnet-18 for lr branch') 
pretrained_super_dict = torch.load('pre-trained resnet-18 for sr branch')

**Comment by franciszchen** [comment]
Sorry for the confusion. (1) In the first stage, the SR model should be trained using ./models/mrcnet.py. The training implementation can be referred to the SR project https://github.com/franciszchen/SWD-Net. (2) The resnet-18 should be ImageNet-pretrained ones, with the URL as https://download.pytorch.org/models/resnet18-5c106cde.pth.
